# Created using https://typeof.net/Iosevka/customizer
[buildPlans.iosevka-personal]
family = "Iosevka Personal"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.iosevka-personal.variants.design]
capital-a = "curly-serifless"
capital-g = "toothed-serifless-hooked"
capital-i = "short-serifed"
capital-j = "serifed-symmetric"
capital-q = "curly-tailed"
capital-r = "curly"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"

g = "double-storey"
i = "hooky"
j = "serifed"
l = "tailed-serifed"
m = "short-leg"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly"
turn-v = "curly"

zero = "slashed"
one = "base"
two = "curly-neck"
three = "flat-top"
four = "closed"
six = "straight-bar"
seven = "straight-serifed"
nine = "straight-bar"

tilde = "low"
asterisk = "penta-low"
underscore = "high"
caret = "high"
brace = "straight"
number-sign = "slanted"
percent = "dots"
lig-ltgteq = "slanted"

[buildPlans.iosevka-personal.variants.italic]
a = "single-storey-serifless"
g = "single-storey-serifless"
i = "tailed-serifed"
k = "straight-serifless"
l = "tailed-serifed"
r = "top-serifed"
y = "cursive"

[buildPlans.iosevka-personal.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-personal.weights.bold]
shape = 700
menu = 700
css = 700
