# Created using https://typeof.net/Iosevka/customizer
[buildPlans.IosevkaPersonal]
family = "Iosevka Personal"
spacing = "fixed"
serifs = "sans"
noCvSS = true
noLigation = true
exportGlyphNames = false

[buildPlans.IosevkaPersonal.variants.design]
capital-i = "short-serifed"

i = "hooky"
l = "zshaped"

three = "flat-top-serifless"

asterisk = "penta-low"
brace = "straight"
percent = "dots"

[buildPlans.IosevkaPersonal.variants.italic]
i = "tailed-serifed"
k = "straight-serifless"
l = "tailed-serifed"

[buildPlans.IosevkaPersonal.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaPersonal.weights.Bold]
shape = 700
menu = 700
css = 700

# build only normal width
[buildPlans.IosevkaPersonal.widths.Normal]
shape = 500
menu = 5
css = "normal"
